#!/usr/bin/env bash
#switch-case islenir
A=1
while ((A<=20));do
	case $A in
		4)
			echo -e "4\nbad luck from China"
			;;
		9)
			echo -e "9\nbad luck from Japan"
			;;
		17)
			echo -e "17\nbad luck from Italy"
			;;
		*)
			echo $A
			;;
	esac
	A=$((A+1))
done
