#!/usr/bin/env bash
# Display filenames after first dash
for file in *; do
    if [ -e "$file" ]; then
        if [ "$file" == *-* ]]; then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
done
