#!/usr/bin/env bash
#school
s="school"
if [ -e "$s" ];then 
	echo "school file exists"
	if [ -s "$s" ]; then 
		echo "school file is not empty"
	else 
		echo "school file is empty"
	fi
	if [ -r "$s" ]; then
		echo "school is a regular file"
	fi
else 
	echo "school file does not exist"
fi
