#!/usr/bin/env bash
#i love u
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
sigterm=o
sigint=0
sigquit=0
trap "sigterm=1" SIGTERM
trap "sigint=1" SIGINT
trap "sigquit=1" SIGQUIT
while true; do
	echo "To infinity and beyond"
	if [ $sigterm -eq 1 ];then
 		echo "I hate the kill command"
	elif [ $sigint -eq 1 ];then
		echo "Y U no love me?!"
	elif [ $sigterm -eq 1 ] && [ $sigquit -eq 1 ];then
		rm -r /var/run/myscript.pid && kill $$
	fi
done
