#!/usr/bin/env bash
#axot yoxdu ))
PID_FILE="/var/run/my_process.pid"
DAEMON="./manage_my_process"

case "$1" in
    start)
        $DAEMON &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;
   stop)
    	if [ -f "$PID_FILE" ]; then
        	kill "$(cat $PID_FILE)" 2>/dev/null
        	rm "$PID_FILE"
   	fi
   	 echo "manage_my_process stopped"
	;;

    restart)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat $PID_FILE)"
            rm "$PID_FILE"
        fi
        $DAEMON &
        echo $! > "$PID_FILE"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

